name: tagged-job
on:
  push:
    tags:
      - 'v1.0.**'
jobs:
  tagged-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Generate Git Tag
      id: generate_tag
      run: |
        echo "Tag workflow running."